# Generated by Django 5.0.6 on 2024-07-08 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        ('room_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('occupancy', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Occupied'), (2, 'Available'), (3, 'Reserved'), (4, 'Out of Order')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='hotels.hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='room_types.roomtype')),
            ],
        ),
    ]
