# Generated by Django 5.0.6 on 2024-07-29 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='occupancy',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Room must have at least 1 people.'), django.core.validators.MaxValueValidator(5, message='Room cannot have more than 5 peoples.')]),
        ),
    ]
