# Generated by Django 5.0.6 on 2024-07-08 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('address', models.CharField(max_length=250)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('number_of_rooms', models.PositiveSmallIntegerField(default=1)),
                ('phone_number', models.CharField(max_length=20)),
                ('star_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Hotel cannot be less than 0 stars'), django.core.validators.MaxValueValidator(5, message='Hotel cannot be higher than 5 stars')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
