# Generated by Django 5.0.6 on 2024-07-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
