# Generated by Django 5.0.6 on 2024-07-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_scheduled_at', models.DateTimeField()),
                ('arrival_date', models.DateTimeField()),
                ('departure_date', models.DateTimeField()),
                ('num_adults', models.PositiveSmallIntegerField()),
                ('num_children', models.PositiveSmallIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-booking_scheduled_at'],
            },
        ),
    ]
